channels:
- conda-forge
- defaults
dependencies:
- python=3.8.6
- numpy=1.19.4
- pip
- cmake=3.18.2
- pip:
  - azureml-core==1.18.0.post1
  - azureml-defaults==1.18.0
  - azureml-telemetry==1.18.0
  - azureml-train-restclients-hyperdrive==1.18.0
  - azureml-train-core==1.18.0
  - torch==1.7.0
  - torchvision==0.8.1
  - horovod==0.21.0
  - tensorboard==2.2
  - future==0.17.1
  - tqdm==4.41.0
  - PyYAML==5.3
  - Pillow